version: '3'

services:
  postgres:
    image: 'postgres:13.4'
    ports:
      - "5433:5432"
    restart: always
    environment:
      POSTGRES_USER: aj
      POSTGRES_PASSWORD: aj
      POSTGRES_DB: ladiwork
    volumes:
      - ./db-data/postgres/:/var/lib/postgres/data/
  
  # redis
  redis:
    image: 'redis:alpine'
    ports:
      - "6380:6379"
    restart: always
    volumes:
      - ./db-data/redis/:/data
    
  mariadb:
    image: 'mariadb:10.6'
    ports:
      - "3308:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=ugo_sample
      - MYSQL_USER=password 
      - MYSQL_PASSWORD=password
    volumes:
      - ./db-data/mariadb:/docker-entrypoint-initdb.d